url: "https://globalstorm.cloud"
baseurl: ""

title: Global Storm
email: contact@globalstorm.cloud
description: "Edge computing platforms for industrial IoT, fleet monitoring, smart cities, and real-time data processing at the source."
author: Global Storm

plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-sitemap

languages: ["en", "pl"]
exclude_from_localizations: ["assets/css", "assets/img", "assets/fonts", "assets/js"]

locale: "en-US"

google_analytics: G-M2N1SW21M1

markdown: kramdown

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: pages
    values:
      layout: page
