collections:
  authors:

plugins:
  - jekyll-multiple-languages-plugin # https://github.com/kurtsson/jekyll-multiple-languages-plugin
  - jekyll-gist # https://github.com/jekyll/jekyll-gist
  - jekyll-paginate

languages: ["en", "pl"]
exclude_from_localizations: ["assets"]

# Pagination 
paginate: 6
paginate_path: /news/page:num/

collections:
  consultancy:
    output: true

  solutions:
    output: true